# version 1.0 HIPRFISR
version: 1
disable_existing_loggers: False
formatters:
    hiprfisrfmt:
        format: '%(asctime)s - %(name)s: [%(levelname)s] %(message)s'
        datefmt: '%m/%d/%Y %I:%M:%S %p'


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: hiprfisrfmt
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: hiprfisrfmt
        filename: Logs/event.log
        maxBytes: 5000000                
        backupCount: 0  # Keep only one file, overwrite when the size limit is reached
    
loggers:
    root:
        level: DEBUG
        handlers: [console,file]
        propagate: False

    fissure:
        level: DEBUG
        handlers: [console, file]
        propagate: False
    
    fissure.dashboard:
        level: DEBUG
        handlers: [console, file]
        propagate: False
        
    fissure.dashboard.frontend:
        level: DEBUG
        handlers: [console, file]
        propagate: False
        
    fissure.dashboard.backend:
        level: DEBUG
        handlers: [console, file]
        propagate: False

    fissure.hiprfisr:
        level: DEBUG
        handlers: [console, file]
        propagate: False

    fissure.pd:
        level: DEBUG
        handlers: [console, file]
        propagate: False

    fissure.tsi:
        level: DEBUG
        handlers: [console, file]
        propagate: False

    fissure.sensor_node:
        level: DEBUG
        handlers: [console, file]
        propagate: False

    fissure.test:
        level: DEBUG
        handlers: [console, file]
        propagate: False
